name: "License checker"

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: Checkout
        uses: actions/checkout@v4
      # step 2
      - name: Check License Header
        run: make verify.copyright
